/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkflowRouteImport } from './routes/workflow'
import { Route as VoiceRouteImport } from './routes/voice'
import { Route as RiskReportRouteImport } from './routes/risk-report'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as KycRouteImport } from './routes/kyc'
import { Route as FrameExtractionRouteImport } from './routes/frame-extraction'
import { Route as FaceDetectionRouteImport } from './routes/face-detection'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CapabilitiesRouteImport } from './routes/capabilities'
import { Route as AnalyzeRouteImport } from './routes/analyze'
import { Route as AiAnalysisRouteImport } from './routes/ai-analysis'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const WorkflowRoute = WorkflowRouteImport.update({
  id: '/workflow',
  path: '/workflow',
  getParentRoute: () => rootRouteImport,
} as any)
const VoiceRoute = VoiceRouteImport.update({
  id: '/voice',
  path: '/voice',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskReportRoute = RiskReportRouteImport.update({
  id: '/risk-report',
  path: '/risk-report',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const KycRoute = KycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => rootRouteImport,
} as any)
const FrameExtractionRoute = FrameExtractionRouteImport.update({
  id: '/frame-extraction',
  path: '/frame-extraction',
  getParentRoute: () => rootRouteImport,
} as any)
const FaceDetectionRoute = FaceDetectionRouteImport.update({
  id: '/face-detection',
  path: '/face-detection',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CapabilitiesRoute = CapabilitiesRouteImport.update({
  id: '/capabilities',
  path: '/capabilities',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzeRoute = AnalyzeRouteImport.update({
  id: '/analyze',
  path: '/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAnalysisRoute = AiAnalysisRouteImport.update({
  id: '/ai-analysis',
  path: '/ai-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-analysis': typeof AiAnalysisRoute
  '/analyze': typeof AnalyzeRoute
  '/capabilities': typeof CapabilitiesRoute
  '/dashboard': typeof DashboardRoute
  '/face-detection': typeof FaceDetectionRoute
  '/frame-extraction': typeof FrameExtractionRoute
  '/kyc': typeof KycRoute
  '/privacy': typeof PrivacyRoute
  '/risk-report': typeof RiskReportRoute
  '/voice': typeof VoiceRoute
  '/workflow': typeof WorkflowRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-analysis': typeof AiAnalysisRoute
  '/analyze': typeof AnalyzeRoute
  '/capabilities': typeof CapabilitiesRoute
  '/dashboard': typeof DashboardRoute
  '/face-detection': typeof FaceDetectionRoute
  '/frame-extraction': typeof FrameExtractionRoute
  '/kyc': typeof KycRoute
  '/privacy': typeof PrivacyRoute
  '/risk-report': typeof RiskReportRoute
  '/voice': typeof VoiceRoute
  '/workflow': typeof WorkflowRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-analysis': typeof AiAnalysisRoute
  '/analyze': typeof AnalyzeRoute
  '/capabilities': typeof CapabilitiesRoute
  '/dashboard': typeof DashboardRoute
  '/face-detection': typeof FaceDetectionRoute
  '/frame-extraction': typeof FrameExtractionRoute
  '/kyc': typeof KycRoute
  '/privacy': typeof PrivacyRoute
  '/risk-report': typeof RiskReportRoute
  '/voice': typeof VoiceRoute
  '/workflow': typeof WorkflowRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ai-analysis'
    | '/analyze'
    | '/capabilities'
    | '/dashboard'
    | '/face-detection'
    | '/frame-extraction'
    | '/kyc'
    | '/privacy'
    | '/risk-report'
    | '/voice'
    | '/workflow'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ai-analysis'
    | '/analyze'
    | '/capabilities'
    | '/dashboard'
    | '/face-detection'
    | '/frame-extraction'
    | '/kyc'
    | '/privacy'
    | '/risk-report'
    | '/voice'
    | '/workflow'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/ai-analysis'
    | '/analyze'
    | '/capabilities'
    | '/dashboard'
    | '/face-detection'
    | '/frame-extraction'
    | '/kyc'
    | '/privacy'
    | '/risk-report'
    | '/voice'
    | '/workflow'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AiAnalysisRoute: typeof AiAnalysisRoute
  AnalyzeRoute: typeof AnalyzeRoute
  CapabilitiesRoute: typeof CapabilitiesRoute
  DashboardRoute: typeof DashboardRoute
  FaceDetectionRoute: typeof FaceDetectionRoute
  FrameExtractionRoute: typeof FrameExtractionRoute
  KycRoute: typeof KycRoute
  PrivacyRoute: typeof PrivacyRoute
  RiskReportRoute: typeof RiskReportRoute
  VoiceRoute: typeof VoiceRoute
  WorkflowRoute: typeof WorkflowRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workflow': {
      id: '/workflow'
      path: '/workflow'
      fullPath: '/workflow'
      preLoaderRoute: typeof WorkflowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voice': {
      id: '/voice'
      path: '/voice'
      fullPath: '/voice'
      preLoaderRoute: typeof VoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk-report': {
      id: '/risk-report'
      path: '/risk-report'
      fullPath: '/risk-report'
      preLoaderRoute: typeof RiskReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kyc': {
      id: '/kyc'
      path: '/kyc'
      fullPath: '/kyc'
      preLoaderRoute: typeof KycRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/frame-extraction': {
      id: '/frame-extraction'
      path: '/frame-extraction'
      fullPath: '/frame-extraction'
      preLoaderRoute: typeof FrameExtractionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/face-detection': {
      id: '/face-detection'
      path: '/face-detection'
      fullPath: '/face-detection'
      preLoaderRoute: typeof FaceDetectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capabilities': {
      id: '/capabilities'
      path: '/capabilities'
      fullPath: '/capabilities'
      preLoaderRoute: typeof CapabilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyze': {
      id: '/analyze'
      path: '/analyze'
      fullPath: '/analyze'
      preLoaderRoute: typeof AnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-analysis': {
      id: '/ai-analysis'
      path: '/ai-analysis'
      fullPath: '/ai-analysis'
      preLoaderRoute: typeof AiAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AiAnalysisRoute: AiAnalysisRoute,
  AnalyzeRoute: AnalyzeRoute,
  CapabilitiesRoute: CapabilitiesRoute,
  DashboardRoute: DashboardRoute,
  FaceDetectionRoute: FaceDetectionRoute,
  FrameExtractionRoute: FrameExtractionRoute,
  KycRoute: KycRoute,
  PrivacyRoute: PrivacyRoute,
  RiskReportRoute: RiskReportRoute,
  VoiceRoute: VoiceRoute,
  WorkflowRoute: WorkflowRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
